# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lsfacts.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(759, 349)
        MainWindow.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 290, 301, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 321, 21))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 321, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 301, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 140, 411, 21))
        self.label_8.setObjectName("label_8")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 341, 21))
        self.label_14.setObjectName("label_14")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 170, 311, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 200, 311, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 230, 371, 21))
        self.label_12.setObjectName("label_12")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(440, 110, 291, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(440, 80, 291, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(440, 140, 291, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(440, 230, 291, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(440, 170, 291, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(440, 20, 291, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(440, 200, 291, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(440, 50, 291, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Life Style Factors"))
        self.pushButton.setText(_translate("MainWindow", "Store Life Style Factors in Data base"))
        self.label_4.setText(_translate("MainWindow", "Alcoholic?"))
        self.label_6.setText(_translate("MainWindow", "Diabetic?"))
        self.label_7.setText(_translate("MainWindow", "Arrhythmiatic?(Irregular heart beat)"))
        self.label_8.setText(_translate("MainWindow", "Doing exercise/walking less than half an hour in a day?"))
        self.label_14.setText(_translate("MainWindow", "Smoker?"))
        self.label_10.setText(_translate("MainWindow", "Living/Working in stressful conditions?"))
        self.label_11.setText(_translate("MainWindow", " High level bad cholesterol?"))
        self.label_12.setText(_translate("MainWindow", "Sleeps more than 8hours/less than 4 hrs.per day?"))
